### ISSUE TITLE
Feature Request: Mouseover display

### ISSUE THREAD

**Issue by brendan-pike** [Bakual/BibleLinkXT#2]
I've been using the Bible Verse Reftagger module and I like the unobtrusive way it displays scripture on mouse on/off. I'm wondering if this could be an option introduced at some point.  It also automatically finds and displays scripture references and while nice that is of less important in my user case.

**Comment by Bakual** [comment]
I'll have a look this evening. I think it may be possible with BibleGateway but not with BibleServer.

**Comment by brendan-pike** [comment]
That would be fine for me :)

**Comment by Bakual** [comment]
I had a look and it doesn't look that easy either. I could load their page into a Bootstrap Popover, but that doesn't look good since it's a full page and not only the verse.
However they offer a Javascript which seems to do what you want: https://www.biblegateway.com/share/#reftag
You may paste that into your template file so it loads on every page or you can use one of the plugins or modules available on JED (https://extensions.joomla.org/category/core-enhancements/coding-a-scripts-integration/) to add it. That should do the trick as well.

**Comment by brendan-pike** [comment]
Thanks again, I've inserted that JS and it does work very well.   However it doesn't work within sermonspeaker scripture references because of the pre/post tagging. eg. {bib=1 Corinthians}.  Is there good benefit of using this feature in ss or should I just put the references directly into the audio description?

**Comment by Bakual** [comment]
If you use that JS, you can just remove the plugin tags in the SermonSpeaker options and disable the BibleLink XT plugin.
Having the references added as scripture, allows to filter the sermons by book. And they can be designed differently. If you just put them into the description, SermonSpeaker doesn't know about them. It's just text then.
Depends what you need :-)

**Comment by brendan-pike** [comment]
I'll give it a try, I'd like to try and retain them.  I'm aiming to try and present sermons something like this site does https://oceandrivechurch.org/sermons I like to filter ideas.
